[package]
name = "jinge-compiler"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
sha2 = "0.11.0"
base64ct = "1.8.3"
swc_core = { version = "65.0.3", features = ["ecma_plugin_transform"] }
swc_ecma_parser = "39.0.2"
swc_common = "21.0.1"
swc_ecma_codegen = "26.0.1"
swc_ecma_transforms_base = "42.0.0"
swc_ecma_transforms_typescript = "46.0.1"
swc_ecma_visit = "23.0.0"
lazy_static = "1.5.0"
hashbrown = "0.17.1"
neon = { version = "1.1.1", features = ["napi-6"] }

# .cargo/config defines few alias to build plugin.
# cargo build-wasi generates wasm-wasi32 binary
# cargo build-wasm32 generates wasm32-unknown-unknown binary.
