[package]
name = "jinge-compiler"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
sha2 = "0.10"
base64ct = "1.6"
swc_core = { version = "14.1", features = ["ecma_plugin_transform"] }
swc_ecma_parser = "9.0"
swc_common = "7.0"
swc_ecma_codegen = "7.0"
swc_ecma_transforms_base = "10.0"
swc_ecma_transforms_typescript = "10.0"
swc_ecma_visit = "7.0"
lazy_static = "1.5"
hashbrown = "0.15"
neon = { version = "1", features = ["napi-6" ] }
ahash = "0.8.11"

# .cargo/config defines few alias to build plugin.
# cargo build-wasi generates wasm-wasi32 binary
# cargo build-wasm32 generates wasm32-unknown-unknown binary.
