[package]
name = "jinge-swc-compiler"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
serde_json = "1"
serde = "1"
sha2 = "0.10"
base64ct = "1.6"
swc_core = { version = "0.99", features = ["ecma_plugin_transform"] }
swc_ecma_parser = { version = "0.148" }
# .cargo/config defines few alias to build plugin.
# cargo build-wasi generates wasm-wasi32 binary
# cargo build-wasm32 generates wasm32-unknown-unknown binary.
