allowBuilds:
  bun: true
  esbuild: false
minimumReleaseAgeExclude:
  - '@oxlint/binding-freebsd-x64@1.83.0'
  - '@oxlint/binding-linux-arm64-gnu@1.83.0'
  - '@oxlint/binding-linux-x64-gnu@1.83.0'
  - '@oxlint/binding-linux-x64-musl@1.83.0'
  - oxfmt@0.68.0
