name: build and release

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    name: ${{ matrix.platform.os_name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: linux-aarch64
            os: ubuntu-20.04
            target: aarch64-unknown-linux-gnu
            bin: libjinge_compiler.so
          - os_name: linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: libjinge_compiler.so
          - os_name: windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: jinge_compiler.dll
            node: x86_64-windows.node
          - os_name: macos-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: libjinge_compiler.dylib
          - os_name: macos-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: libjinge_compiler.dylib
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm -v
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: 'build'
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: '--locked --release'
          strip: true
      - name: Copy to bindings directory
        run: mv target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }} platform/${{ matrix.platform.os_name }}/index.node
      - name: Publish to npm
        working-directory: platform/${{ matrix.platform.os_name }}
        run: npm config set _authToken ${{secrets.NPM_TOKEN}} && npm publish
